import { COLORS } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    paddingTop: 30,
    backgroundColor: COLORS.background,
    flex: 1,
    paddingHorizontal: 20,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  titleText: {
    fontSize: 22,
    fontWeight: "600",
    color: COLORS.secondary,
  },
  mainContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  profilePicture: {
    width: 150,
    height: 150,
    resizeMode: "contain",
    borderRadius: 125,
    marginBottom: 40,
  },
  helloTextContainer: {
    alignItems: "center",
    marginBottom: 50,
  },
  helloText: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.secondary,
    textAlign: "center",
  },
  helloSubText: {
    marginTop: 15,
    fontSize: 16,
    color: COLORS.darkgray,
    textAlign: "center",
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  buttonsSection: {
    width: "85%",
    alignItems: "center",
    gap: 15,
  },
  actionButtonMain: {
    flexDirection: "row",
    backgroundColor: COLORS.primary,
    paddingVertical: 18,
    paddingHorizontal: 30,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    elevation: 8,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  actionButtonMainText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 10,
  },
  actionButtonSecondary: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: COLORS.primary,
    paddingVertical: 18,
    paddingHorizontal: 30,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  actionButtonSecondaryText: {
    color: COLORS.primary,
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 10,
  },
  cameraPermissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.light,
    borderRadius: 15,
  },
  cameraPermissonButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    backgroundColor: COLORS.primary,
    borderWidth: 1,
    borderColor: COLORS.darkgray,
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 24,
    maxWidth: 250,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
});
